import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
// import ClickRedirectWrapper from "./wrapper";
import Footer from "./_components/Footer";
import { AuthProvider } from "./_context/AuthContext";
import { Toaster } from "sonner";
// import AdsProvider from "./adsProvider";



const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "AniLook - Watch All type of anime Free",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="no-scrollbar">
      <body
        className={`${outfit.className} bg-neutral-950 no-scrollbar`}
      >
        {/* <ClickRedirectWrapper>  */}
        {/* // <AdsProvider> */}
          <AuthProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
          </AuthProvider>
        {/* // </AdsProvider> */}
        {/* </ClickRedirectWrapper>  */}
      </body>
    </html >
  );
}
