import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
// import ClickRedirectWrapper from "./wrapper";
import Footer from "./_components/Footer";
import { AuthProvider } from "./_context/AuthContext";



const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "AniLook - Watch All type of anime Free",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${outfit.className} bg-[#2d2b2c] no scrollbar`}
      >
        {/* <ClickRedirectWrapper>  */}
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
       {/* </ClickRedirectWrapper>  */}
      </body>
    </html>
  );
}
